### ISSUE TITLE
expect ingress-bfe chart package 

### ISSUE THREAD

**Issue by zkfopen** [bfenetworks/ingress-bfe#18]
At present, it is very convenient to deploy ingress-nginx using helm. Really, it is very convenient to use helm. Therefore, we look forward to providing ingress-bfe chart package.

**Comment by daimg** [comment]
Good point. The charts are under developing, and will be available soon. Thanks for your attention.

**Comment by daimg** [comment]
Helm chart is available, refer to https://github.com/bfenetworks/ingress-bfe/blob/main/docs/en_us/deployment.md#helm
