### ISSUE TITLE
Use BFE in Kubernetes by Ingress

### ISSUE THREAD

**Issue by zhugelianglongming** [bfenetworks/ingress-bfe#2]
first commit for BFE ingress controller, enable BFE in Kubernetes by Ingress

**Comment by zhangbo1882** [comment]
Any plans for the ingress controller ?

**Comment by clarinette9** [comment]
> Any plans for the ingress controller ?

Hi,  we are working on this and will publish BFE ingress controller soon, in September.

**Comment by iyangsj** [comment]
#3
